#!/usr/bin/env node
/**
 * Generates the built-in property orders shipped by the plugin:
 *
 * - `src/orders/devtools.js` — replicates Chrome DevTools' Computed panel grouped
 *   view, built from the DevTools sources vendored in vendor/ (see
 *   scripts/lib/devtools-sources.js for what those are).
 * - `src/orders/recess.js` — snapshot of the Recess/Bootstrap order from
 *   stylelint-config-recess-order (devDependency).
 *
 * Usage: node scripts/generate-orders.js # use vendor/ (fetch if missing) node
 * scripts/generate-orders.js --refresh # re-download DevTools sources
 */

import { existsSync } from "node:fs";
import { access, mkdir, writeFile } from "node:fs/promises";
import { createRequire } from "node:module";
import path from "node:path";
import { fileURLToPath } from "node:url";

import * as prettier from "prettier";
import recessConfig from "stylelint-config-recess-order";

import { buildGroups, createMetadata } from "./lib/build-devtools-order.js";
import {
  loadSources,
  refreshSources,
  vendorDir,
} from "./lib/devtools-sources.js";

const rootDir = path.dirname(path.dirname(fileURLToPath(import.meta.url)));
const ordersDir = path.join(rootDir, "src", "orders");
const args = new Set(process.argv.slice(2));

// Groups before this index are structural resets (`composes`, `all`), which
// should still take precedence over `color-scheme`.
const COLOR_SCHEME_TARGET_INDEX = 2;

/**
 * @param {string} name
 * @param {string} header
 * @param {object} order
 */
async function writeOrder(name, header, order) {
  const source = `${header}\nexport default ${JSON.stringify(order)};\n`;
  const formatted = await prettier.format(source, { parser: "babel" });
  await writeFile(path.join(ordersDir, `${name}.js`), formatted);
  const count = order.groups.flatMap((g) => g.properties).length;
  console.log(`✓  Wrote src/orders/${name}.js (${count} properties)`);
}

await mkdir(ordersDir, { recursive: true });

// ── DevTools order ───────────────────────────────────────────────────────────

const haveVendor = await access(path.join(vendorDir(rootDir), "meta.json"))
  .then(() => true)
  .catch(() => false);

if (args.has("--refresh") || !haveVendor) {
  console.log("Fetching DevTools sources from chromium.googlesource.com …");
  const meta = await refreshSources(rootDir);
  console.log(`✓  Vendored sources at commit ${meta.commit ?? "(unknown)"}`);
}

const sources = await loadSources(rootDir);
const metadata = createMetadata(
  sources.generatedProperties,
  sources.generatedAliasesFor,
);
const devtoolsGroups = buildGroups({
  categoryOrder: sources.categoryOrder,
  categorizedProperties: sources.categorizedProperties,
  metadata,
});

await writeOrder(
  "devtools",
  `// Generated by scripts/generate-orders.js — do not edit.
// Chrome DevTools Computed panel grouped view order.
// Source: ${sources.meta.repository}
// Commit: ${sources.meta.commit ?? "unknown"} (${sources.meta.fetchedAt})`,
  {
    name: "devtools",
    groups: devtoolsGroups.map(({ name, properties }) => ({
      name,
      properties,
    })),
  },
);

// ── Recess order ─────────────────────────────────────────────────────────────

const recessGroups = recessConfig.rules["order/properties-order"];
if (
  !Array.isArray(recessGroups) ||
  !recessGroups.every((g) => Array.isArray(g.properties))
) {
  throw new Error(
    "stylelint-config-recess-order changed shape — update this generator",
  );
}

const require = createRequire(import.meta.url);
let recessPkgDir = path.dirname(
  require.resolve("stylelint-config-recess-order"),
);
while (!existsSync(path.join(recessPkgDir, "package.json"))) {
  recessPkgDir = path.dirname(recessPkgDir);
}
const recessPkg = require(path.join(recessPkgDir, "package.json"));

await writeOrder(
  "recess",
  `// Generated by scripts/generate-orders.js — do not edit.
// Recess/Bootstrap property order, snapshot of stylelint-config-recess-order@${recessPkg.version} (MIT).
// https://github.com/stormwarning/stylelint-config-recess-order
// Patched: -webkit-user-select moved before user-select, color-scheme group
// moved to the top (see applyRecessPatches below).`,
  {
    name: "recess",
    groups: applyRecessPatches(
      recessGroups.map(({ properties }) => ({ properties })),
    ),
  },
);

/**
 * Fixes upstream inconsistencies in stylelint-config-recess-order's property
 * order without hand-editing the generated snapshot.
 *
 * @param {{ properties: string[] }[]} groups
 * @returns {{ properties: string[] }[]}
 */
function applyRecessPatches(groups) {
  return moveColorSchemeGroupFirst(groups).map(swapUserSelectOrder);
}

/**
 * Upstream lists `user-select` before `-webkit-user-select`, unlike its other
 * prefixed/standard pairs (`-ms-touch-action`/`touch-action`,
 * `-webkit-line-clamp`/`line-clamp`) where the prefix comes first so the
 * standard property wins the cascade in engines that support both.
 *
 * @param {{ properties: string[] }} group
 * @returns {{ properties: string[] }}
 */
function swapUserSelectOrder({ properties }) {
  const standard = properties.indexOf("user-select");
  const prefixed = properties.indexOf("-webkit-user-select");
  if (standard === -1 || prefixed === -1 || prefixed < standard) {
    return { properties };
  }
  const patched = [...properties];
  [patched[standard], patched[prefixed]] = [
    patched[prefixed],
    patched[standard],
  ];
  return { properties: patched };
}

/**
 * `color-scheme` selects which UA color palette (light/dark) other color
 * properties resolve against, so it should be declared before any of them — the
 * same reasoning that puts custom properties (`--*`) first (handled outside
 * this order file, in property-order.js's CUSTOM_PROPERTIES_TIER). Upstream
 * instead places it alongside unrelated color/contrast properties mid-list.
 *
 * @param {{ properties: string[] }[]} groups
 * @returns {{ properties: string[] }[]}
 */
function moveColorSchemeGroupFirst(groups) {
  const index = groups.findIndex(({ properties }) =>
    properties.includes("color-scheme"),
  );
  if (index === -1) return groups;

  const patched = [...groups];
  const [group] = patched.splice(index, 1);
  patched.splice(COLOR_SCHEME_TARGET_INDEX, 0, group);
  return patched;
}
